### ISSUE TITLE
Is it legal?

### ISSUE THREAD

**Issue by dev-abir** [hhhrrrttt222111/Dorkify#3]
Is it legal to do google dorking? And moreover according the readme, this application will be used deliberately to find security holes in web applications. You should mention that how end-users should use this application.

**Comment by dev-abir** [comment]
Oh, you have added a notice, in dorkify.py, nevermind... Better if you add that to readme as well...

**Comment by hhhrrrttt222111** [comment]
> Oh, you have added a notice, in dorkify.py, nevermind... Better if you add that to readme as well...

Sure.
Thanks
